### ISSUE TITLE
该机器人是否更新？

### ISSUE THREAD

**Issue by Touchafish** [OwONetworks/OwOBot#1]

**Comment by TheresaQWQ** [comment]
大概率是不会更新了，但是插件大概还是可以用的？迁移到其他机器人框架应该是没问题的w

**Comment by Touchafish** [comment]
> 大概率是不会更新了，但是插件大概还是可以用的？迁移到其他机器人框架应该是没问题的w

苏苏可爱的苏苏✧(◍˃̶ᗜ˂̶◍)✩
